### ISSUE TITLE
Road to v1.1.0

### ISSUE THREAD

**Issue by carlopi** [duckdb/community-extensions#85]
Hi all (@hafenkran, @lmangani, @rustyconover, @Dtenwolde, @JAicewizard, @arjenpdevries, @isaacbrodsky, @ywelsch, @pdet, and @Maxxen)!

We are getting very close to the next release, and we have now a mechanism for testing community extensions versus the latest duckdb branch, using that as approximation of the status of the release.

#### Recent changes
Changes that happened recently:
* there is a mechanism, outlined in [this PR](https://github.com/duckdb/community-extensions/pull/81) to optionally specify the commit to use for the upcoming release. It's a matter of specifying `ref_next`. If that's not present, `ref` property would be used.
* we did set up (and triggered) a workflow to test any current extensions against duckdb main on all relevant platforms, detailed results are https://github.com/duckdb/community-extensions/actions/workflows/test_all.yml for the latest run.
* we are testing, going forward for the next days, new extensions or changes to descriptors both against duckdb `v1.0.0` and duckdb `main` branch

This pieces together should allow extensions developers/maintainers to check whether extensions are compatible with changes that happened in DuckDB between version v1.0.0 and now.

Once v1.1.0 will be released, as part of the release processes `ref_next` (if present) would become `ref`, and extensions built and (when successful) published on `v1.1.0`.

#### Testing results
| extension | detected problem |
| -- | -- |
| bigquery | compilation error |
| chsql | compilation error |
| lindel | compilation error |
| prql | compilation error |
| scrooge | test failing |

Other extension looks to be working fine.
Complete results are at https://github.com/duckdb/community-extensions/actions/runs/10619930977/job/29438643392

#### How to fix detected incompatibilities
[quack](https://github.com/duckdb/community-extensions/blob/main/extensions/quack/description.yml), the demo extension, had also a problem when tested vs main duckdb, so that now also work as a demo of the intended workflow:
1. problem is detected while compiling vs main
2. in the extension repository the problem is fixed (and potentially duckdb submodule is updated to a recent duckdb commit)
3. a PR is sent to add a `ref_next` (or possibly changing `ref`, if the changes are backward compatible) (see the commit: https://github.com/duckdb/community-extensions/commit/dc86e730709ce60245ee68ddde1e062e01161bb8)
4. CI tests this, and once merged the extension is properly set

----

We are super grateful for the involvement, and we plan on iterating on this to make it even smoother, feedback is very welcome.

Thanks everyone!

**Comment by carlopi** [comment]
Minor update: DuckDB v1.1.0 is now penciled in for next Monday, 9th of September: https://duckdb.org/docs/dev/release_calendar#upcoming-releases

**Comment by carlopi** [comment]
Update: DuckDB v1.1.0 is out, and most extension have been build / updated yesterday.

It was the first change in version, and I think it went relatively smooth.

I am aware of 3 extensions not successfully working on v1.1.0 at the moment:
* bigquery, tracked at https://github.com/hafenkran/duckdb-bigquery/issues/21
* duckpgq, tracked at https://github.com/cwida/duckpgq-extension/issues/149
* scrooge, tracked at https://github.com/pdet/Scrooge-McDuck/issues/36

If assistance is welcome, please do ping.

**Comment by carlopi** [comment]
I guess we are set, thanks, closing this.

Now up to bugfix in `v1.1.1`, currently planned for next Monday
