### ISSUE TITLE
Windows (MSVC 14.51) builds failing for all recent PRs — DuckDB v1.5.3 vendored fmt uses removed stdext::checked_array_iterator

### ISSUE THREAD

**Issue by avaitla** [duckdb/community-extensions#2061]
## Summary

All recent PRs fail the **`windows_amd64` (x64-windows-static-release)** build while compiling DuckDB's own vendored `fmt`. This is not extension-specific — it blocks every current Windows PR.

Failing object: `third_party/fmt/CMakeFiles/duckdb_fmt.dir/format.cc.obj`

```
duckdb/third_party/fmt/include/fmt/format.h(326): error C2653: 'stdext': is not a class or namespace name
duckdb/third_party/fmt/include/fmt/format.h(326): error C2061: syntax error: identifier 'checked_array_iterator'
duckdb/third_party/fmt/include/fmt/format.h(336): error C7525: inline variables require at least '/std:c++17'
```

## Root cause

GitHub's `windows-latest` image moved to **MSVC 14.51** (toolset 19.51.x, ships with VS 2026 18.6), which **removed the deprecated `stdext::checked_array_iterator`**. DuckDB **v1.5.3** — currently pinned via `duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.5-variegata` — still uses it in its vendored fmt:

```cpp
// third_party/fmt/include/fmt/format.h:326 @ v1.5.3
template <typename T> using checked_ptr = stdext::checked_array_iterator<T*>;
```

This is duckdb/duckdb#22704, fixed in duckdb/duckdb#22706 ("Remove checked_array_iterator from third_party/fmt", merged to `main` 2026-05-16). **That fix is on `main` but is NOT in the `v1.5.3` tag**, so the build community-extensions pins still contains the broken code.

## Evidence

- Same DuckDB source in both: the `v1.5.3` tag is commit `14eca11`; verified `format.h` on `v1.5.3` still has `stdext::checked_array_iterator`, while `main` no longer does.
- The only thing that changed is the compiler: a build on MSVC **14.44** passes; MSVC **14.51** fails on identical source.
- Recent PRs failing identically: #2051, #2052, #2054, #2056. PRs that passed earlier (e.g. #2019, June 5) ran on the older MSVC 14.44 image — i.e. a pure toolchain-bump regression, not a code change.

## Suggested fixes

1. **Bump the pinned DuckDB** to a build containing duckdb/duckdb#22706 (a v1.5.x patch with the fmt update, or a `main` commit ≥ `76232a4`). — clean fix
2. **Interim unblock:** pin the Windows MSVC toolset to ≤14.44 in the `_extension_distribution.yml` reusable workflow (e.g. `-vcvars_ver=14.44` or pin the runner image) until DuckDB is bumped.

**Comment by avaitla** [comment]
### How the DuckDB pin works, and the recommendation

The DuckDB version is pinned in `.github/workflows/build.yml` as a literal default that's passed to the reusable workflow:

```yaml
# build.yml
DUCKDB_VERSION: ${{ inputs.duckdb_version || 'v1.5.3' }}
...
uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.5-variegata
with:
  duckdb_version: ${{ inputs.duckdb_version || 'v1.5.3' }}
  ci_tools_version: ${{ inputs.ci_tools_version || 'v1.5-variegata' }}
```

So a "bump" means changing the `'v1.5.3'` literal (it appears in several places: the `DUCKDB_VERSION` env, the build/docs/deploy `duckdb_version` inputs, and the coupled `COMMUNITY_EXTENSION_VCPKG_COMMIT` selection) to a newer DuckDB ref. `_extension_distribution.yml` then checks out duckdb/duckdb at that ref.

**Catch: there is no fixed release tag to bump to yet.** Latest tag is `v1.5.3`; #22706 is only on `main` (merge `76232a4`). There's no `v1.5.4`/`v1.6.0`. So the clean "bump the tag" fix isn't available today.

**Recommendation (in order):**

1. **Now — pin the Windows MSVC toolset to ≤14.44** in the `_extension_distribution.yml@v1.5-variegata` Windows job (e.g. `-vcvars_ver=14.44`, or pin the runner image instead of `windows-latest`). This is the only thing that unblocks all Windows PRs immediately, since no fixed DuckDB release exists.

2. **When available — bump the DuckDB pin.** Once DuckDB ships a `v1.5.x` patch (or `v1.6.0`) containing #22706, change the `'v1.5.3'` defaults in `build.yml` to that tag (and the matching vcpkg commit). Alternatively, cherry-pick #22706 onto the DuckDB branch used by the `v1.5-variegata` build line so the pinned source carries the fmt fix without waiting for a release.

Option 1 is the immediate unblock; option 2 is the durable fix.
