### PR TITLE
sitting_duck 1.15.1

### PR DESCRIPTION
**Pull request by teaguesterling**
Bumps `sitting_duck` from 1.11.0 to **1.15.1**, with `ref` and `ref_next` both at `648b570`.

### Why `648b570` and not the `v1.15.1` tag

`648b570` is 3 commits past tag `v1.15.1` (`b52cf325`), deliberately — those 3 commits are what make the extension compile on the v2.0 line:

```
648b570 Merge pull request #175 from teaguesterling/fix/doc-helper-version-agnostic
8568563 fix(doc_helper): see through a set's element pointers too
114920e fix(doc_helper): read argument types through both DuckDB APIs
```

Pinning `b52cf325` (the literal v1.15.1 tag) fails the prerelease leg:

```
src/include/function_doc_helper.hpp:15: error: 'class duckdb::ScalarFunction' has no member named 'arguments'
  :35  ...shared_ptr<const duckdb::ScalarFunction>...     has no member named 'arguments'
  :76  ...shared_ptr<const duckdb::TableFunction, true>... has no member named 'arguments'
```

`v2.0-cyanoptera` keeps `arguments` public on `SimpleNamedParameterFunction` (`TableFunction`'s base) but routes `ScalarFunction` through `FunctionSignature`, where it sits behind `GetArguments()`. The set errors are a second, separate change: `ScalarFunctionSet::functions` holds values on v1.5.4 and `shared_ptr<const ScalarFunction>` on the v2.0 line.

### Changes since 1.11.0

`ast_select` CSS-selector correctness batch:
- `:scope` / `:in-scope` split (`:scope` = "is a scope boundary"; containment is `:in-scope`)
- Bare type selectors are **exact**, not prefix; `[type^=]`/`[type$=]`/`[type*=]` added
- `[file]`/`[line]` attribute filters; `ast_selector_for` ("copy selector")
- Malformed selectors raise instead of silently over- or under-matching
- `:has`/adjacency fixes; `IS_CONSTITUENT` for construct sub-parts
- `:called-by`/`:calls` are direct and lambda-aware, bounded via `scope.function` (fixes an OOM on large tables)

In 1.15.x:
- `ast_unparse`: pluggable rules-based AST unparser, with default rules across 27 languages
- Functions are discoverable from `duckdb_functions()`
- DuckDB v2.0 compatibility: `ConstantExpression` → `Literal`, plus the doc-helper argument-type fix above

### Supersedes

duckdb/community-extensions#2764 (closed) added only `repo.ref_next`, leaving `version` at 1.11.0 and `ref` at `b8c06a84`. This PR does both properly.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01AjgU52vGS3mpSAwwgJD5C4

### CODE REVIEW

**Comment by teaguesterling** [comment]
Updated to **1.14.1** (`ref`/`ref_next` → `c0e5e7f`, tag `v1.14.1`). 1.14.1 makes `::callees` direct/lambda-aware, completing the call-graph consistency (`:calls`/`:called-by`/`::callers`) landed in 1.14.0.

**Comment by lghavami** [comment]
Hi @teaguesterling, I'm seeing some build failures in CI. Could you take a look? Thanks!

**Comment by teaguesterling** [comment]
Will do! I botched something on what should have been a small fix.

**Comment by teaguesterling** [comment]
Updated to **v1.15.0** (`17b509d`).

Highlights in 1.15.0:
- **AST Unparser (`ast_unparse`, `ast_unparse_rules`)**: Full code generation engine supporting roundtrip code transformation with custom rules, spacing, and layouts across all supported tree-sitter grammars.
- **Discoverability**: All scalar and table functions now register rich parameter names, descriptions, and examples discoverable via `duckdb_functions()`.
- **Docs Refresh**: Comprehensive documentation and how-to guides for AST transformation and code queries.

All target builds (Linux x64/arm64, macOS x64/arm64, Windows MSVC/MinGW, WebAssembly mvp/threads/eh) in `Community Extension Build` have completed successfully.

**Comment by teaguesterling** [comment]
Parking this bump until sitting_duck's DuckDB-v2.0 (test_against_latest) validation is green. The stable build passes; the v2.0 forward-validation currently reds on an ast_select planning-cost regression (test timeouts) plus a catalog parameter-name difference. Will reopen / resubmit once v2.0 is green. Thanks!
